services:
  # A Docker web service
  - type: web
    name: wikirace-en
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn wiki_race.asgi -k uvicorn.workers.UvicornWorker
    region: frankfurt
    plan: free
    branch: master
#    healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: wikirace-en-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: elephant-en
          property: connectionString
      - fromGroup: common-wikirace
  - type: redis
    name: wikirace-en-redis
    region: frankfurt 
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
  - type: web
    name: wikirace-ru
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn wiki_race.asgi -k uvicorn.workers.UvicornWorker
    region: frankfurt
    plan: free
    branch: ru
#    healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: wikirace-ru-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: elephant-ru
          property: connectionString
      - key: WIKI_API
        value: https://ru.wikipedia.org/w/api.php
      - fromGroup: common-wikirace
  - type: redis
    name: wikirace-ru-redis
    region: frankfurt 
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free

databases:
  - name: elephant-en
    plan: free
    region: frankfurt 
    postgresMajorVersion: 14
  - name: elephant-ru
    plan: free
    region: frankfurt 
    postgresMajorVersion: 14

envVarGroups:
  - name: common-wikirace
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: wiki_race.settings
      - key: DEBUG
        value: true
      - key: USE_SECURE_WEBSOCKETS
        value: true
