# Generated by Django 3.2.9 on 2021-11-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki_app", "0002_auto_20211127_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
